# Generated by Django 4.2.23 on 2025-11-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fefu_lab', '0002_alter_instructor_options_remove_course_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='max_students',
            field=models.PositiveIntegerField(default=30, verbose_name='Максимум студентов'),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL-адрес'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Название курса'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Активен'), ('COMPLETED', 'Завершен')], default='ACTIVE', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта'),
        ),
    ]
